Java enums? With extra Visitor please!
ippontech/blog-usa pull request #125
Opened 2019-07-02 13:32 UTC by Gregoriz

Hello,

I've finished my article a way to deal with Java enums.

I'm wondering if I should add the DDD/Craft tags.

Where can I find the list of available tags ?

Thanks for the review !

2019-07-02 13:36 UTC, Throckmortra commented
Hey Gregory, I'll review this today and send you an invite to the ghost backend so you can view tags. Make sure your author name matches your Ghost name. Thanks!

2019-07-02 19:08 UTC, parrycj commented on posts/java-enums-with-extra-visitor-please.md
> +During one of my mission, the team was facing a huge number of enums and many business logic was based upon their values. The visitor pattern was our shield against unpredicted edge cases. It became
```suggestion
During one of my missions, the team was dealing with a large number of enums and there was business logic based upon their values. The visitor pattern was our shield against unpredicted edge cases. It became our standard way to deal with enums in the code base.
```

2019-07-02 19:53 UTC, Gregoriz commented on posts/java-enums-with-extra-visitor-please.md
> +Using enums can be, however, tricky when it is about making decision according to its values. As the enum evolves, every part of the code where it has been used as a condition must be checked. If a l
Me neither, i'll commit your suggestion and keep the conversation opened in case anyone has the answer

2019-07-02 19:58 UTC, Gregoriz commented on posts/java-enums-with-extra-visitor-please.md
> +For instance, metals could be split into two sub assets: base metals and precious metals. Any already existing code based on `AssetClass.METAL` will have to be reworked to take this change into accou
The same comment has been made about the FR version. I corrected it and will do so for the EN version as well

2019-07-02 20:31 UTC, Gregoriz commented on posts/java-enums-with-extra-visitor-please.md
> +For instance, metals could be split into two sub assets: base metals and precious metals. Any already existing code based on `AssetClass.METAL` will have to be reworked to take this change into accou
What do you think about:

 Any code based on `AssetClass.METAL` will have to be reworked to take those two new values into account. This refactoring will bring no new business value but will exposing an already working feature to the risk of regressions.

2019-12-09 08:05 UTC, gelhaimer commented
Any news for my PR ?

2021-04-14 14:00 UTC, yhippa commented
@gelhaimer for whatever reason, this fell to the wayside. Is this post still valid? If so, I will make it a priority to review and approve. If not I'll close it.

2021-04-14 16:19 UTC, gelhaimer commented
Hello,

I think it's still valuable. The review has been left over, so it will maybe need to be finalized before.

2021-04-15 13:59 UTC, yhippa reviewed
This is an amazing post. I actually did something similar to this in a project a while ago but didn't recognize that the Visitor pattern could be useful here. It is not as elegant as what you did. It can be real helpful as a lightweight rules engine where you need to have different execution paths based on an enum.

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +Enums can be seen as a group of strongly typed constants. Their several use cases include: attributing a strong semantic to values, limiting and validating available values for data, enhancing code r
```suggestion
Enums can be seen as a group of strongly typed constants. Their several use cases include: attributing strong semantics to values, limiting and validating available values for data, and enhancing code readability.
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +However, using enums can be tricky when it comes to making decisions according to its values. As the enum evolves, each part of the code where it has been used as a condition must be checked. If many
```suggestion
Using enums can be tricky when it comes to making decisions according to its values. As the enum evolves, each part of the code where it has been used as a condition must be checked. If many decisions have been based on an enum's values, maintaining the code base can be a nightmare. A single missed verification can lead to corruption of the entire system.
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +But is there a way to reduce the impact of enums' evolutions on the code base?
```suggestion
Is there a way to reduce the impact of enums' impact on the code base?
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +Consider the `AssetClass` enum which represents the different group of tradable commodities:
```suggestion
Consider the `AssetClass` enum which represents distinct groups of tradable commodities:
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +Using this defaulting mechanism silences any addition of a new value inside the enum. It requires a check of any piece of code using `AssetClass` as a conditioner without any guarantee that an oversi
```suggestion
Even though each enum value should have a handler adding a default handler here ensures that there is some way to handle an arbitrary `AssetClass`.  This is helpful when an enum value has been added but is missed in other parts of the codebase.
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +The last problem is probably the least obvious. Using the switch-case statement generates a strong coupling between the business logic and the enum's values, breaking the open/close principle.
```suggestion
The last problem is probably the least obvious. Using the switch-case statement generates a strong coupling between the business logic and the enum's values, breaking the (open-closed principle)[https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle].
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +How can we break this coupling while offering the ability to contextualize the decision making to the enum's values? The answer is in the title: let's use the Visitor pattern.
```suggestion
How can we break this coupling while offering the ability to contextualize the decision making to the enum's values? The answer is in the title: let's use the (Visitor pattern)[https://en.wikipedia.org/wiki/Visitor_pattern].
```

2021-04-15 13:59 UTC, yhippa commented on posts/java-enums-with-extra-visitor-please.md
> +During one of my missions, the team was dealing with a large number of enums and there was business logic based upon their values. The visitor pattern was our shield against unpredicted edge cases. I
```suggestion
During one of my projects, the team was dealing with a large number of enums and there was business logic based upon their values. The visitor pattern was our shield against unpredicted edge cases. It became our standard way to deal with enums in the code base.
```

2021-04-20 19:56 UTC, nnightingale14 requested changes

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +Even though each enum value should have a handler adding a default handler here ensures that there is some way to handle an arbitrary `AssetClass`.  This is helpful when an enum value has been added
Even though each enum value should have a handler, adding a default handler here ensures that there is some way to handle an arbitrary `AssetClass`.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +For instance, metals could be split into two sub assets: base metals and precious metals. Any already existing code based on `AssetClass.METAL` will have to be reworked to take this change into accou
Any code based on `AssetClass.METAL` will have to be reworked to take those two new values into account. This refactoring will not bring any new business value, but will instead expose an already working feature to the risk of regressions.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +# Visitor pattern to the rescue
Visitor Pattern to the Rescue

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +First off, we need to create an interface which will be used as a contract between the enum and the code relying on its values.
First, we need to create an interface which will be used as a contract between the enum and the code relying on its values.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +Now it's necessary to update the enum to make it accept any implementation of the `AssetClassVisitor`.
It is now necessary to update the enum to make it accept _any_ implementation of the `AssetClassVisitor`.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +It can be observed that each value of `AssetClass` is responsible for calling the appropriate method of `AssetClassVisitor`. Values of `AssetClass` can now be ignored as the semantic is brought by th
Each value of `AssetClass` is responsible for calling the appropriate method of `AssetClassVisitor`.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +# Add a new asset class
Add a new Asset Class

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +After this, the code will light up like a Christmas Tree: it does not compile anymore. The compiler should be thanked for doing such a great job! All those highlighted errors show that some part of t
All of those highlighted errors show that some part of the code is not designed to handle the new value yet. Let's correct this by using an exception: the existing features are not yet available for livestock and meat.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +# In a nutshell
In a Nutshell

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +During one of my projects, the team was dealing with a large number of enums and there was business logic based upon their values. The visitor pattern was our shield against unpredicted edge cases. I
The visitor pattern was our shield against unpredictable edge cases.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +Using this pattern is not necessary if your enums are purely descriptive. However, bringing the heavy artillery is definitively worth the extra cost. Breaking the coupling between enum's values and t
Breaking the coupling between an enum's values and the business logic offers flexibility, while the compiler provides an instantaneous feedback about potential oversight and edge cases.

2021-04-20 19:56 UTC, nnightingale14 commented on posts/java-enums-with-extra-visitor-please.md
> +title: "Java enums? With extra Visitor please!"
"Java Enums? With extra Visitor, please!"

2022-12-20 14:48 UTC, closed without merging