The Trusty Bucket - Introduction and Basics
ippontech/blog-usa pull request #168
Opened 2021-02-11 18:54 UTC by brianknight10

Hello!

Please review my introductory post to the AWS S3 service. This one is quite basic, covering what is S3, buckets, and objects. The aim is to layer on the complexity bit by bit with each post, but this one just introduces the series and level-sets on the basics.

Appreciate any and all feedback! Thanks for reviewing! :smile:

2021-02-12 16:59 UTC, matthewreed26 requested changes
Simple to follow. Very quick read. Good example. Just a few things I saw

2021-02-12 16:59 UTC, matthewreed26 commented on posts/the-trusty-bucket-introduction-and-basics.md
> +_Buckets_ are storage containers for your _objects_. A bucket is the highest level of organization within S3 and is a convenient boundary for billing aggregation and access control. You can choose a
```suggestion
_Buckets_ are storage containers for your _objects_. A bucket is the highest level of organization within S3 and is a convenient boundary for billing aggregation and access control. You can choose a single [AWS Region](https://aws.amazon.com/about-aws/global-infrastructure/regions_az/) for any bucket you create. Within that region, S3 will replicate your objects across multiple datacenters to ensure durability and reliability.
```

2021-02-12 16:59 UTC, matthewreed26 commented on posts/the-trusty-bucket-introduction-and-basics.md
> +## Checking out the bucket
```suggestion
## Checking out the bucket settings
```

2021-02-12 16:59 UTC, matthewreed26 commented on posts/the-trusty-bucket-introduction-and-basics.md
> +An empty bucket is not very useful. We need to put some data in it! I always tell people that you could put a ham sandwich in S3, so I have photos of three delicious sandwiches that we can upload.
Love this haha

2021-02-12 16:59 UTC, matthewreed26 commented on posts/the-trusty-bucket-introduction-and-basics.md
> +
Perhaps a few sources would be helpful to list at the end?

2021-02-12 18:42 UTC, brianknight10 commented
Thanks @matthewreed26 - great suggestions!

2021-02-12 19:51 UTC, matthewreed26 approved these changes
LGTM

2021-02-16 17:38 UTC, bescott1 approved these changes

2021-02-16 17:38 UTC, merged