[blog] Git: Dealing with broken branches
ippontech/blog-usa pull request #183
Opened 2021-08-09 20:09 UTC by bescott1

2021-08-17 18:51 UTC, gkontos commented on posts/git-tips.md
> +For example, let's say you branched off `develop` with your `feature` branch. Your branches have diverged and develop now has 10 new commits, and your feature branch has 100 commits. You've tried reb
```suggestion
For example, let's say you branched off `develop` with your `feature` branch. Your branches have diverged and develop now has 10 new commits, and your feature branch has 100 commits. You've tried rebasing, but you end up in an endless loop of conflicts.
```

2021-08-17 18:54 UTC, gkontos commented on posts/git-tips.md
> +* Click the merge and squash button
I'm not sure if you have the time, but a graphic would help illustrate what you are talking about here.

2021-08-17 18:56 UTC, gkontos commented on posts/git-tips.md
> +It's important to note that start isn't inclusive and end is. To make things simpler I've just decided to use a notation that will change it to both sides being inclusive. The `^` symbol refers to th
```suggestion
It's important to note that start isn't inclusive and end is. To make things simpler I've decided to use a notation that will change it to both sides being inclusive. The `^` symbol refers to the parent of a commit, thus:
```
'just' is a meaningless modifier at best.  At worst it makes your decision sound flippant.

2021-08-24 13:04 UTC, nnightingale14 requested changes

2021-08-24 13:04 UTC, nnightingale14 commented on posts/git-tips.md
> +The other problem I've run into is when some commits from upstream somehow end up mixed with your feature branch. This typically happens when someone has done a bad merge/rebase. If you catch the pro
```suggestion
The other problem I've run into is when some commits from upstream somehow end up mixed with your feature branch. This typically happens when someone has done a bad merge/rebase. If you catch the problem right away, you can reset your branch to what it was just prior to the merge using [reflog](https://git-scm.com/docs/git-reflog) if you've pushed or by resetting if you haven't:
```

2021-08-24 13:04 UTC, nnightingale14 commented on posts/git-tips.md
> +Then try to merge/rebase again. However, if you have commits after the bad ones then you'll need to extract those commits. You could use interactive rebase for this, but I prefer to use [cherry-pick]
```suggestion
Then try to merge/rebase again. However, if you have commits after the bad ones, then you will need to extract those commits. You could use interactive rebase for this, but I prefer to use [cherry-pick](https://git-scm.com/docs/git-cherry-pick). Let's assume you have five commits with a bad one in the middle:  1 2 **3** 4 5, with **3** being the bad one and **0** being the parent commit of the feature branch.
```

2021-08-24 13:04 UTC, nnightingale14 commented on posts/git-tips.md
> +It's important to note that start isn't inclusive and end is. To make things simpler I've decided to use a notation that will change it to both sides being inclusive. The `^` symbol refers to the par
```suggestion
It is important to note that start is **_not_** inclusive while end **_is_**. To make things simpler, I have decided to use a notation that will change **both** sides to be inclusive. The `^` symbol refers to the parent of a commit, thus:
```

2021-08-24 13:04 UTC, nnightingale14 commented on posts/git-tips.md
> +You would then test your branch to make sure you haven't broken anything. You could force push this onto your previous broken branch, or just keep working off this one.
```suggestion
You would then test your branch to make sure you haven't broken anything. You could force push this onto your previous broken branch or just keep working off this one.
```

2021-08-24 13:04 UTC, nnightingale14 commented on posts/git-tips.md
> +You would then test your branch to make sure you haven't broken anything. You could force push this onto your previous broken branch, or just keep working off this one.
May want to include a hooking conclusion with our typical selling point as well.

2021-09-03 17:43 UTC, merged