Python in production part 4 of 5
ippontech/blog-usa pull request #223
Opened 2022-10-18 18:57 UTC by lward27

This one is a bit long, but lot's of good information and lessons learned contained within.

2022-10-18 21:04 UTC, lward27 commented
From Nathan Shurte - switch unit file to user space, not system space. Seek slack thread https://ipponusa.slack.com/archives/C54D5S91B/p1666119730635589

2022-10-19 14:01 UTC, lanefu approved these changes
good job see suggestions

2023-01-26 17:10 UTC, pkrish123 requested changes

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +Following is an explanation of each line.
```suggestion
Here is an explanation of each line.
```

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +SCP stands for **S**ecure **C**opy.  It is a simple command line utility that transfers files from your local machine, to a remote server (or the other way around!).  If you are more comfortable with
You've only highlighted the S & C of SCP. Isn't SCP, Secure Copy Protocol?

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +SCP stands for **S**ecure **C**opy.  It is a simple command line utility that transfers files from your local machine, to a remote server (or the other way around!).  If you are more comfortable with
You might also want to highlight what makes the transfer secure specifically here versus just running a cp

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +My command looks like this (DON'T RUN THIS ONE!):
```suggestion
My command looks like this (***DON'T RUN THIS ONE!***): 
```

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +My command looks like this (DON'T RUN THIS ONE!):
Bolding and italicizing for extra emphasis!

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +An example (DON'T RUN THIS ONE!):
```suggestion
An example (***DON'T RUN THIS ONE!***):
```

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +The next step after copying both files on to our server, is to log into our server and complete our setup.  This next step will only need to be completed one time, and then it is good forever!
```suggestion
After copying both files onto our server, the next step is to complete our setup.  This next step will only need to be completed once; it is good forever!
```

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +These three commands tell systemd to look for new unit files, add them to the list of things to start on boot, and then start the service.  To verify our service is indeed running, we will use anothe
patter -> pattern

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +Use your browser to navigate to the site and you should see the new message `{"Message":"Hello, World! From North Carolina"}`.  When testing locally, we simply set an Environment Variable, but system
```suggestion
Use your browser to navigate the site and see the new message `{"Message":"Hello, World! From North Carolina"}`.  When testing locally, we set an Environment Variable, but systemd has an option to load an environment file.  Earlier, we created a file called `simple_api.conf`.  We will put that file on our Linux server in the `/etc/default/simple_api.conf` location.  Let's go ahead and update our unit file and then we will load it all onto our server.
```

2023-01-26 17:10 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +Let's say that down the road, I move to Virgina.  If I had hardcoded my location into my source code, I would need to rebuild, and relaunch my appilication to reflect this change.  Using an environme
```suggestion
Let's say that down the road, I move to Virginia.  If I had hardcoded my location into my source code, I would need to rebuild and relaunch my application to reflect this change.  Using an environment file in our systemd unit file enables us to change aspects of our program *without* having to rebuild it.  With a small application like this, rebuilding would be manageable, but things get complicated as applications get bigger.  Let's update our location to Virginia and then call it a day.
```

2023-01-26 17:12 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +Welcome back to the Python in Production series.  In the [third part](https://templinkplaceholder) of the series, we learned how to convert our program into a runnable binary file.  Now that we have
You can update the link for Part 3 now that it's published as well!

2023-01-27 15:51 UTC, pkrish123 commented on posts/python-in-production-part-4-of-5.md
> +An example (DON'T RUN THIS ONE!):
Bolding and Italicizing for extra emphasis!

2023-03-27 13:23 UTC, pkrish123 approved these changes

2023-04-13 18:55 UTC, merged