Taking chatgpt for an impromptu spin
ippontech/blog-usa pull request #238
Opened 2023-01-24 20:17 UTC by matthewreed26

2023-01-26 16:55 UTC, pkrish123 requested changes
I love this! Maybe you can add a small blurb before the conclusion pointing people to try ChatGPT themselves, and how to install it?

2023-01-26 16:55 UTC, pkrish123 commented on posts/taking-chatgpt-for-an-impromptuspin.md
> +[OpenAI](https://openai.com/blog/chatgpt/)'s brainchild, "[ChatGPT](https://chat.openai.com/)," is all the rage right now and is identified/poised to be a massive disrupter in the software engineerin
"identified/poised" reads oddly to me here. I would pick one or the other.

2023-01-26 16:55 UTC, pkrish123 commented on posts/taking-chatgpt-for-an-impromptuspin.md
> +Hello Brave New World?
I love this response! It really ties in with how alien, and foreign ChatGPT's self-generated origin story is!

2023-01-27 15:47 UTC, matthewreed26 commented
> I love this! Maybe you can add a small blurb before the conclusion pointing people to try ChatGPT themselves, and how to install it?

Sure, I can encourage readers to go signup for a free account and try it out for themselves! But no installing as it is web-hosted haha.

2023-01-27 15:49 UTC, pkrish123 commented
> > I love this! Maybe you can add a small blurb before the conclusion pointing people to try ChatGPT themselves, and how to install it?
> 
> Sure, I can encourage readers to go signup for a free account and try it out for themselves! But no installing as it is web-hosted haha.

Oh! Then the console parts are just the web UI! got it!

2023-01-27 16:53 UTC, pkrish123 approved these changes

2023-02-22 20:56 UTC, merged