Elementary setup blog
ippontech/blog-usa pull request #258
Opened 2023-06-21 13:32 UTC by tbridges-ippon

2023-06-21 14:08 UTC, pkrish123 requested changes
I have one wording change, but other than that it's good to go!

2023-06-21 16:13 UTC, nnightingale14 approved these changes

2023-06-21 16:13 UTC, nnightingale14 commented on posts/dbt-elementary-snowflake.md
> +  - DBT
```suggestion
  - dbt
```

2023-06-21 16:13 UTC, nnightingale14 commented on posts/dbt-elementary-snowflake.md
> +title: "Enhance your DBT Data Monitoring with Elementary"
```suggestion
title: "Enhance your dbt Data Monitoring with Elementary"
```

2023-06-21 16:13 UTC, nnightingale14 commented on posts/dbt-elementary-snowflake.md
> +<p> This blog aims to provide a guide on implementing the Elementary package with DBT. The primary functionalities of this guide focus on: </p>
```suggestion
<p> This blog aims to provide a guide on implementing the Elementary package with dbt. The primary functionalities of this guide focus on: </p>
```

2023-06-21 17:22 UTC, portillosc commented on posts/dbt-elementary-snowflake.md
> +
^ the two previous paragraphs are concise and well worded.

2023-06-22 18:22 UTC, pkrish123 approved these changes

2023-06-22 19:00 UTC, merged